name: Build and deploy React app to Azure Web App - mymoneyfront

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # This is required for actions/checkout

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Instalar dependências e buildar o React
        run: |
          npm install
          npm run build

      - name: Verificar se o build foi gerado
        run: ls -la ./build

      - name: Compactar apenas a pasta build
        run: zip -r release.zip build

      - name: Upload artifact para o job de deploy
        uses: actions/upload-artifact@v4
        with:
          name: react-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Baixar o artifact do job de build
        uses: actions/download-artifact@v4
        with:
          name: react-app

      - name: Descompactar artifact
        run: unzip release.zip

      - name: Login no Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_F243D9CA6AC2437A9432DBBAD306CC5E }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_0CAC76305B5548D5B81C4DB36AB92584 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_0D901F72921340A59CF1C6FA00DBBAAD }}

      - name: 'Deploy para o Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'mymoneycontasfront'
          slot-name: 'Production'
          package: './build'
