name: Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    # Checkout do código
    - name: Checkout code
      uses: actions/checkout@v2
    
    # Instalação das dependências
    - name: 'Install dependencies'
      run: |
        npm install

    # Build do projeto
    - name: 'Build project'
      run: |
        npm run build

    # Deploy para o Azure usando o publish profile
    - name: 'Deploy to Azure'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'mymoneycontasfrontend'  # Substitua pelo nome correto do seu App Service no Azure
        slot-name: 'production'  # Ou o nome do seu slot específico
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}  # Use o secret com o conteúdo do publish profile
